### ISSUE TITLE
TODO: post-training synthetic patching

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/ismir2017_chords#1]
- [x] Decouple predictor bias and weights
- [x] Generate examples from all chord classes
- [x] Implement weight-freeze, retraining
